
[functions.generate-survey-cover]
enabled = true
verify_jwt = true
import_map = "./functions/generate-survey-cover/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-survey-cover/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-survey-cover/*.html" ]

[functions.generate-survey-questions]
enabled = true
verify_jwt = true
import_map = "./functions/generate-survey-questions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-survey-questions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-survey-questions/*.html" ]
